import { Code2 } from 'lucide-react';
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiOpenjdk,
  SiSharp,
  SiCplusplus,
  SiC,
  SiGo,
  SiRust,
  SiPhp,
  SiRuby,
  SiSwift,
  SiKotlin,
  SiHtml5,
  SiCss,
  SiDart,
  SiScala,
  SiR,
  SiPerl,
  SiLua,
  SiHaskell,
  SiElixir,
  SiClojure,
  SiGnubash,
  SiJson,
  SiYaml,
  SiMarkdown,
  SiMysql,
} from 'react-icons/si';

const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  java: SiOpenjdk,
  csharp: SiSharp,
  cpp: SiCplusplus,
  c: SiC,
  go: SiGo,
  rust: SiRust,
  php: SiPhp,
  ruby: SiRuby,
  swift: SiSwift,
  kotlin: SiKotlin,
  html: SiHtml5,
  css: SiCss,
  dart: SiDart,
  scala: SiScala,
  r: SiR,
  perl: SiPerl,
  lua: SiLua,
  haskell: SiHaskell,
  elixir: SiElixir,
  clojure: SiClojure,
  bash: SiGnubash,
  shell: SiGnubash,
  json: SiJson,
  yaml: SiYaml,
  markdown: SiMarkdown,
  sql: SiMysql,
};

export function LanguageIcon({ id, className }: { id: string; className?: string }) {
  const Icon = ICON_MAP[id.toLowerCase()] ?? Code2;
  return <Icon className={className} />;
}
